name: Build Acumatica Customization

# on:
#   push:
#     branches:
#       - 'release/v*'
#     paths:
#       - 'AcumaticaUSSFenceCustomizations[2024R1]/**'
#       - 'Customizations/AcumaticaUSSFenceCustomizations[2024R1]/**'

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to (e.g. Dev)'
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: self-hosted

    env:
      SOLUTION: 'AcumaticaUSSFenceCustomizations[2024R1].sln'
      PROJECT: 'AcumaticaUSSFenceCustomizations[2024R1]\AcumaticaUSSFenceCustomizations[2024R1].csproj'
      ZIP_OUTPUT: 'AcumaticaUSSFenceCustomizations[2024R1].zip'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Checkout DLL Repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: ZingworksChetan/dll-store
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     path: dlls

      # - name: Copy DLLs from dll-store to project bin
      #   shell: Powershell
      #   run: |
      #     $dest = "Customization\AcumaticaUSSFenceCustomizations[2024R1]\bin\Release"
      #     if (-Not (Test-Path -LiteralPath $dest)) {
      #       New-Item -ItemType Directory -Force -Path $dest | Out-Null
      #     }
      #     Copy-Item -Path "dlls\*.dll" -Destination $dest -Force

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Project
        run: msbuild $env:PROJECT /p:Configuration=Release
        shell: Powershell
        env:
          PROJECT: AcumaticaUSSFenceCustomizations[2024R1]\AcumaticaUSSFenceCustomizations[2024R1].csproj
          NUGET_PACKAGES: ${{ github.workspace }}\.nuget\packages

      - name: Copy DLL to Customization Bin
        shell: Powershell
        run: |
          $projectName = "AcumaticaUSSFenceCustomizations`[2024R1`]"
          $dllName = "AcumaticaUSSFenceCustomizations[2024R1].dll"

          # Full source path
          $source = Join-Path -Path $PWD.Path -ChildPath "$projectName\bin\Release"

          # Destination inside the Customizations folder
          $destination = Join-Path -Path $PWD.Path -ChildPath "Customizations\$projectName\Bin"

          Write-Host "Copying built DLL from: $source"
          Write-Host "Destination path: $destination"

          if (Test-Path -LiteralPath $source) {
           New-Item -ItemType Directory -Force -Path $destination | Out-Null

            $dllSourcePath = Join-Path $source $dllName
            Copy-Item -LiteralPath $dllSourcePath -Destination $destination -Force
            Write-Host "DLL copied to $destination"
          } else {
            Write-Host "Source path not found: $source"
          }

      - name: Build CustomizationPackageTools.exe
        run: |
            cd CustomizationPackageTools
            dotnet build --configuration Release
            cd ..
        shell: Powershell

      - name: Build Customization Package
        id: build
        shell: Powershell
        run: |
          $date = Get-Date -Format "yyyyMMdd"
          $zipName = "AcumaticaUSSFenceCustomizations[2024R1-$($date)]"
          echo "zipName=$zipName" >> $env:GITHUB_OUTPUT
          Powershell ./buildCustomization.ps1 $zipName

      - name: Run Publish Customization
        shell: powershell
        env:
          ACUMATICA_URL: ${{ secrets.ACUMATICA_URL }}
          ACUMATICA_USERNAME: ${{ secrets.ACUMATICA_USERNAME }}
          ACUMATICA_PASSWORD: ${{ secrets.ACUMATICA_PASSWORD }}
        run: |
          $zipName = "${{ steps.build.outputs.zipName }}"
          Write-Host "Publishing package: $zipName"
          ./publishCustomization.ps1 $zipName

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.zipName }}
          path: build/*.zip

